### ISSUE TITLE
Flatbread Options do not work

### ISSUE THREAD

**Issue by da5idw** [aidanscode/six-twelve-food-stores#1]
Flatbread options small, medium, and large for both cold and toasted temperatures does not work when selected in meal builder. 

Test Case - Add Flatbread ingredient

**Comment by aidanscode** [comment]
I don't know what you mean by "does not work"
But here's video of it working for me: https://youtu.be/5BLpCwDT-ng
To be safe, make sure you're on the new `bugfix/forward-slash-paths` branch if that hasn't been merged with master yet
