### ISSUE TITLE
Cannot remove spread after selecting one.

### ISSUE THREAD

**Issue by da5idw** [aidanscode/six-twelve-food-stores#3]
After selecting an spread option, user cannot remove it - they currently can only restart entire sandwich process. They should be able to remove only the spread option. They should also be able to select a 'no spread' option. 

Test Case - Remove Spread

**Comment by ghost** [comment]
Sorry, meant 'toppings' not spread.

**Comment by aidanscode** [comment]
Good catch, will add a "back to toppings" button on the final view that allows them to go back and change their selection, like the button on all the other selection views

**Comment by aidanscode** [comment]
Will implement tomorrow night
