### ISSUE TITLE
Temperature, Bread Type, Meats, and Toppings do not show images.

### ISSUE THREAD

**Issue by da5idw** [aidanscode/six-twelve-food-stores#4]
In the admin page, temperature, bread type, meats, and toppings do not show current ingredient images or when user adds an new ingredient/image. 

Test Case - Admin adds ingredient

**Comment by aidanscode** [comment]
They all worked for me, but lucky for you I happened to just set up Pop! OS as a dual boot on my desktop and saw that they won't render on here
I believe this had to do with certain areas of the code using back slashes for paths, which Linux doesn't seem to like. I switched them to forward slashes and then suddenly the images started showing

Check out the latest PR ^

After pulling down the changes, run `php artisan migrate:fresh` then `php artisan db:seed`

**Comment by aidanscode** [comment]
Fix confirmed
